name: Continous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run test
    runs-on: unbuntu-latest
    steps:
      -uses: actions/checkout@master
      -uses: actions/setup-node@master
      -with:
        node-version: 21
      -run: npm ci
      -run: npm build
      -run: npm test
